### ISSUE TITLE
При создании набора файлов возникает ошибка

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_filebucket#1]
В ходе выполнения операции возникла неожиданная ошибка. Сообщение об ошибке: 
Неизвестная исключительная ситуация UnicodeEncodeError, cериализатор file_bucket, атрибут files.

URL: http://demo.nextgis.ru/rekod

**Comment by BishopGIS** [comment]
Ошибка касается не только набора файлов. А вообще всех файлов на русском - векторный слой, растр. Таким образом, если НГВ входит в такое состояние, то для российского пользователя (у которого 90% файлов названо по-русски), система становится совершенно неюзабельной.

**Comment by drnextgis** [comment]
Похоже, что проблема решена путём добавления следующей строки в секцию `uwsgi` в файле `production.ini`:

```
[uwsgi]
env = LANG=ru_RU.UTF-8
```

**Comment by BishopGIS** [comment]
Больше не воспроизводится
