### ISSUE TITLE
Возможно утечка памяти

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_filebucket#16]
После создания 5 бакетов объем памяти занятой NGW вырос с 1.5Гб до 9Гб

![Снимок экрана 2020-01-21 в 20 53 33](https://user-images.githubusercontent.com/1708122/72829580-1b590f00-3c90-11ea-8b2a-1551bad4ec38.png)

**Comment by edpop** [comment]
Ты говоришь не про оперативную память? Загрузил три архива по 170МБ, ничего вроде не скакнуло, тем более так резко.
Если про память на диске, то сейчас файлы копируются из `file_upload` в `file_storage`, поэтому занимают в два раза больше места, пока `file_upload` не почистится.

**Comment by BishopGIS** [comment]
Именно про оперативную. 170 это слишком мало - тут грузили порядка 3 Гб в 6 бакетов (http://mggtdev.nextgis.com/resource/1072).

**Comment by dezhin** [comment]
Судя по всему проблема того как развернуто (возможно специфично для gunicorn). На uwsgi не воспроизводится, на pserve + debug_toolbar в принципе ожидаемо.
